import { Article, Perk, Ad, UserDashboard, Transaction } from "./types";

export const articles: Article[] = [
  {
    id: "1",
    title: "The Hidden Architecture of Your Credit Score",
    slug: "hidden-architecture-credit-score",
    excerpt:
      "Most people treat their credit score like a mystery. It isn't. It's an engineered system — and once you see the blueprint, you can build within it.",
    content: "",
    category: "Credit Score Optimization",
    author: "Credit Coffee Editorial",
    imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800",
    publishedAt: "2026-04-01",
    featured: true,
  },
  {
    id: "2",
    title: "Business Credit Stacking: A Quiet Strategy",
    slug: "business-credit-stacking",
    excerpt:
      "Separate your personal liability from your business ambitions. Here's how seasoned founders layer business credit lines without a personal guarantee.",
    content: "",
    category: "Business Credit",
    author: "Credit Coffee Editorial",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800",
    publishedAt: "2026-03-28",
    featured: true,
  },
  {
    id: "3",
    title: "Banking Relationships That Pay You Back",
    slug: "banking-relationships-pay-back",
    excerpt:
      "The right banking relationship isn't just about where you keep your money — it's about what doors open when you do.",
    content: "",
    category: "Banking Relationships",
    author: "Credit Coffee Editorial",
    imageUrl: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=800",
    publishedAt: "2026-03-25",
    featured: false,
  },
  {
    id: "4",
    title: "Travel Hacking 101: Points, Miles, and Silence",
    slug: "travel-hacking-101",
    excerpt:
      "The best travel hackers don't brag. They book first-class flights for the price of a latte. Here's the playbook they quietly follow.",
    content: "",
    category: "Travel Hacking",
    author: "Credit Coffee Editorial",
    imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=800",
    publishedAt: "2026-03-20",
    featured: false,
  },
  {
    id: "5",
    title: "The Cashback Equation: Turn Spending Into Income",
    slug: "cashback-equation",
    excerpt:
      "Every dollar you spend can return a fraction of itself — if you architect your card portfolio correctly. Let's run the numbers.",
    content: "",
    category: "Cashback Systems",
    author: "Credit Coffee Editorial",
    imageUrl: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800",
    publishedAt: "2026-03-15",
    featured: false,
  },
  {
    id: "6",
    title: "Tax Positioning for the Strategically Minded",
    slug: "tax-positioning-strategically-minded",
    excerpt:
      "This isn't tax advice. It's a framework for thinking about tax efficiency the way institutions do — not the way consumers are taught.",
    content: "",
    category: "Tax Positioning",
    author: "Credit Coffee Editorial",
    imageUrl: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800",
    publishedAt: "2026-03-10",
    featured: false,
  },
];

export const perks: Perk[] = [
  {
    id: "p1",
    title: "Premium Cashback Returns",
    description: "Earn 1–5% cashback on every purchase. Stack categories for maximum return across dining, travel, groceries, and more.",
    category: "credit-cards",
    subcategory: "Cashback",
    requirements: "Good to excellent credit (670+)",
    value: "$500–$2,000/year",
    icon: "💳",
    featured: true,
  },
  {
    id: "p2",
    title: "Travel Rewards & Points",
    description: "Accumulate transferable points and airline miles. Access 1:1 transfer partners and unlock outsized redemption value.",
    category: "credit-cards",
    subcategory: "Travel Rewards",
    requirements: "Good credit (700+), travel spend pattern",
    value: "2–10x point multipliers",
    icon: "✈️",
    featured: true,
  },
  {
    id: "p3",
    title: "Airport Lounge Access",
    description: "Priority Pass, Centurion Lounges, Delta Sky Clubs. Turn layovers into experiences with complimentary food, drinks, and showers.",
    category: "credit-cards",
    subcategory: "Lounge Access",
    requirements: "Premium card holder ($450+ annual fee)",
    value: "$1,200+/year in lounge visits",
    icon: "🛋️",
    featured: false,
  },
  {
    id: "p4",
    title: "Sign-Up Bonuses",
    description: "Welcome offers ranging from $200 to $1,000+ in statement credits, points, or miles after meeting initial spend requirements.",
    category: "credit-cards",
    subcategory: "Sign-Up Bonuses",
    requirements: "New applicant, meet minimum spend ($500–$5,000)",
    value: "$200–$1,000+",
    icon: "🎁",
    featured: true,
  },
  {
    id: "p5",
    title: "0% APR Intro Periods",
    description: "Finance large purchases or consolidate debt with 0% interest for 12–21 months. A strategic tool for capital preservation.",
    category: "credit-cards",
    subcategory: "0% APR",
    requirements: "Good credit (680+)",
    value: "12–21 months interest-free",
    icon: "📊",
    featured: false,
  },
  {
    id: "p6",
    title: "Purchase Protection & Warranties",
    description: "Extended warranties, purchase protection against damage/theft, return protection, and cell phone insurance — built into your card.",
    category: "credit-cards",
    subcategory: "Purchase Protection",
    requirements: "Pay with eligible card",
    value: "Up to $10,000 per claim",
    icon: "🛡️",
    featured: false,
  },
  {
    id: "p7",
    title: "High-Yield Savings Accounts",
    description: "Park your reserves in accounts earning 4.5%+ APY. No minimums, FDIC insured, fully liquid.",
    category: "banking",
    subcategory: "High-Yield Savings",
    requirements: "Open account with partner bank",
    value: "4.5%+ APY",
    icon: "🏦",
    featured: true,
  },
  {
    id: "p8",
    title: "Business Banking Bonuses",
    description: "Earn $300–$750 for opening a business checking account and meeting deposit/transaction requirements.",
    category: "banking",
    subcategory: "Business Banking",
    requirements: "Registered business entity (LLC, Corp)",
    value: "$300–$750 bonus",
    icon: "💼",
    featured: false,
  },
  {
    id: "p9",
    title: "Private Banking Access",
    description: "Dedicated relationship managers, preferential rates, and exclusive investment opportunities for high-balance clients.",
    category: "banking",
    subcategory: "Private Banking",
    requirements: "$250,000+ in deposits/investments",
    value: "Custom rate negotiations",
    icon: "🔑",
    featured: false,
  },
  {
    id: "p10",
    title: "Wire Fee Waivers & Early Deposit",
    description: "Eliminate wire transfer fees ($25–$50 each) and access direct deposits up to 2 days early with qualifying accounts.",
    category: "banking",
    subcategory: "Fee Waivers",
    requirements: "Qualifying account tier",
    value: "$300+/year in saved fees",
    icon: "⚡",
    featured: false,
  },
  {
    id: "p11",
    title: "Business Credit Lines (No PG)",
    description: "Access revolving credit lines using your business EIN only. No personal guarantee required once your business credit profile matures.",
    category: "advanced",
    subcategory: "Business Credit",
    requirements: "2+ years in business, established D&B/Experian business profile",
    value: "$10,000–$250,000 credit lines",
    icon: "🏢",
    featured: true,
  },
  {
    id: "p12",
    title: "SBA Loan Eligibility",
    description: "Qualify for government-backed small business loans with favorable terms: low rates, long repayment, and partial guarantees.",
    category: "advanced",
    subcategory: "SBA Loans",
    requirements: "US-based small business, good personal credit",
    value: "Up to $5M at competitive rates",
    icon: "📋",
    featured: false,
  },
  {
    id: "p13",
    title: "Amex / Chase Relationship Tiers",
    description: "Unlock invitation-only products like Amex Centurion or Chase Private Client. Higher limits, concierge services, and priority support.",
    category: "advanced",
    subcategory: "Relationship Tiers",
    requirements: "Significant spend history ($50K+/year)",
    value: "Invitation-only products",
    icon: "👑",
    featured: false,
  },
  {
    id: "p14",
    title: "Asset-Based Lending & Margin",
    description: "Borrow against your investment portfolio at favorable rates. Access liquidity without selling positions or triggering tax events.",
    category: "advanced",
    subcategory: "Asset-Based Lending",
    requirements: "$100K+ in brokerage assets",
    value: "Borrow at 5–7% against portfolio",
    icon: "📈",
    featured: false,
  },
];

export const ads: Ad[] = [
  {
    id: "ad1",
    title: "NerdWallet: Find Your Best Card",
    description: "Compare 200+ credit cards side-by-side. Cashback, travel, business — filtered to your credit profile. Takes 60 seconds.",
    sponsor: "NerdWallet",
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
    linkUrl: "#",
    category: "Credit Cards",
    reward: 0.50,
    duration: 30,
  },
  {
    id: "ad2",
    title: "Mercury: Banking for Startups",
    description: "FDIC-insured accounts, team management, and API integrations built for scaling companies. No fees, no minimums.",
    sponsor: "Mercury",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
    linkUrl: "#",
    category: "SaaS Platforms",
    reward: 0.75,
    duration: 30,
  },
  {
    id: "ad3",
    title: "Lemonade: Insurance Reimagined",
    description: "Renters, homeowners, pet, and life insurance powered by AI. Get a quote in 90 seconds, claims paid in minutes.",
    sponsor: "Lemonade",
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800",
    linkUrl: "#",
    category: "Insurance",
    reward: 0.60,
    duration: 30,
  },
  {
    id: "ad4",
    title: "Ramp: Corporate Cards That Save",
    description: "Automated expense management, 1.5% cashback on everything, and real-time spend controls. Built for finance teams.",
    sponsor: "Ramp",
    imageUrl: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800",
    linkUrl: "#",
    category: "Credit Cards",
    reward: 0.65,
    duration: 30,
  },
  {
    id: "ad5",
    title: "Wealthfront: Automated Investing",
    description: "Tax-loss harvesting, direct indexing, and high-yield cash accounts — all automated. $500 minimum to start.",
    sponsor: "Wealthfront",
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800",
    linkUrl: "#",
    category: "Financial Tools",
    reward: 0.55,
    duration: 30,
  },
  {
    id: "ad6",
    title: "Brex: Business Spend Platform",
    description: "Corporate cards, bill pay, reimbursements, and travel — unified in one platform. No personal guarantee required.",
    sponsor: "Brex",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800",
    linkUrl: "#",
    category: "SaaS Platforms",
    reward: 0.70,
    duration: 30,
  },
];

export const mockTransactions: Transaction[] = [
  { id: "t1", type: "earn", amount: 0.50, description: "Ad viewed: NerdWallet", createdAt: "2026-04-04T10:30:00Z" },
  { id: "t2", type: "earn", amount: 0.75, description: "Ad viewed: Mercury", createdAt: "2026-04-03T14:15:00Z" },
  { id: "t3", type: "referral", amount: 1.25, description: "Referral bonus: @alex", createdAt: "2026-04-02T09:00:00Z" },
  { id: "t4", type: "earn", amount: 0.60, description: "Ad viewed: Lemonade", createdAt: "2026-04-01T16:45:00Z" },
  { id: "t5", type: "bonus", amount: 2.00, description: "7-day reading streak bonus", createdAt: "2026-03-31T08:00:00Z" },
  { id: "t6", type: "earn", amount: 0.65, description: "Ad viewed: Ramp", createdAt: "2026-03-30T11:20:00Z" },
  { id: "t7", type: "earn", amount: 0.55, description: "Ad viewed: Wealthfront", createdAt: "2026-03-29T13:10:00Z" },
  { id: "t8", type: "referral", amount: 0.80, description: "Referral bonus: @jordan", createdAt: "2026-03-28T10:00:00Z" },
];

export const mockDashboard: UserDashboard = {
  name: "Demo User",
  email: "demo@credit.coffee",
  streak: 12,
  totalEarned: 47.85,
  adsViewed: 64,
  articlesRead: 28,
  referralCode: "BREW-X7K9",
  referralCount: 5,
  wallet: {
    balance: 47.85,
    tokenSymbol: "BEAN",
    address: "0x1a2b...9f8e",
  },
  transactions: mockTransactions,
  savedPerks: ["p1", "p4", "p7", "p11"],
};

export const categories = [
  "All",
  "Credit Score Optimization",
  "Business Credit",
  "Banking Relationships",
  "Travel Hacking",
  "Cashback Systems",
  "Tax Positioning",
] as const;

export const perkCategories = [
  { id: "credit-cards" as const, label: "Credit Card Perks", icon: "💳" },
  { id: "banking" as const, label: "Banking Perks", icon: "🏦" },
  { id: "advanced" as const, label: "Advanced Financial", icon: "📈" },
];

export const adCategories = [
  "All",
  "Credit Cards",
  "SaaS Platforms",
  "Insurance",
  "Financial Tools",
] as const;
